name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: SwitchGiftDataManager.sln
      Project_Path: SwitchGiftDataManager.CommandLine/SwitchGiftDataManager.CommandLine.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Clean previous build artifacts
      run: dotnet clean ${{ env.Project_Path }} --configuration ${{ matrix.configuration }}

    - name: Install dependencies and build
      run: |
        dotnet restore ${{ env.Project_Path }}
        dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Upload Linux CommandLine build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux.CommandLine.App
        path: SwitchGiftDataManager.CommandLine/bin